[package]
name = "HomeAssistantHDMIStateSetter"
version = "1.0.0"
edition = "2021"

[dependencies]
reqwest = {version="0.12.12", features=["blocking"]}
serde = {version="1.0.217", features=["derive"]}
serde_json = "1.0.135"

[[bin]]
name = "home_assistant_hdmi_state_setter"
path = "main.rs"
